# Generated by Django 4.2.7 on 2023-12-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CombineLexus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("類型", models.CharField(max_length=50, null=True, verbose_name="類型")),
                ("車種", models.CharField(max_length=50, null=True, verbose_name="車種")),
                ("VIN", models.CharField(max_length=50, null=True, verbose_name="VIN")),
                (
                    "中文等級",
                    models.CharField(max_length=50, null=True, verbose_name="中文等級"),
                ),
                (
                    "出廠年月",
                    models.CharField(max_length=50, null=True, verbose_name="出廠年月"),
                ),
                (
                    "排氣量_x",
                    models.CharField(max_length=50, null=True, verbose_name="排氣量_x"),
                ),
                (
                    "車身型式",
                    models.CharField(max_length=50, null=True, verbose_name="車身型式"),
                ),
                ("車重", models.CharField(max_length=50, null=True, verbose_name="車重")),
                (
                    "價格_x",
                    models.CharField(max_length=50, null=True, verbose_name="價格_x"),
                ),
                (
                    "車牌號碼",
                    models.CharField(max_length=50, null=True, verbose_name="車牌號碼"),
                ),
                (
                    "價格_y",
                    models.CharField(max_length=50, null=True, verbose_name="價格_y"),
                ),
                (
                    "車身座位",
                    models.CharField(max_length=50, null=True, verbose_name="車身座位"),
                ),
                (
                    "變速系統",
                    models.CharField(max_length=50, null=True, verbose_name="變速系統"),
                ),
                (
                    "動力型式",
                    models.CharField(max_length=50, null=True, verbose_name="動力型式"),
                ),
                (
                    "定速巡航",
                    models.CharField(max_length=50, null=True, verbose_name="定速巡航"),
                ),
                (
                    "蜂鳴式倒車輔助系統",
                    models.CharField(
                        max_length=50, null=True, verbose_name="蜂鳴式倒車輔助系統"
                    ),
                ),
                (
                    "倒車影像輔助",
                    models.CharField(max_length=50, null=True, verbose_name="倒車影像輔助"),
                ),
                (
                    "前方駐車雷達",
                    models.CharField(max_length=50, null=True, verbose_name="前方駐車雷達"),
                ),
                (
                    "循跡防滑控制系統",
                    models.CharField(max_length=50, null=True, verbose_name="循跡防滑控制系統"),
                ),
                (
                    "車道偏離警示系統",
                    models.CharField(max_length=50, null=True, verbose_name="車道偏離警示系統"),
                ),
                (
                    "車道變換輔助系統",
                    models.CharField(max_length=50, null=True, verbose_name="車道變換輔助系統"),
                ),
                (
                    "ACC主動跟車系統",
                    models.CharField(
                        max_length=50, null=True, verbose_name="ACC主動跟車系統"
                    ),
                ),
                (
                    "車道維持輔助系統",
                    models.CharField(max_length=50, null=True, verbose_name="車道維持輔助系統"),
                ),
                (
                    "AEB自動緊急煞車系統",
                    models.CharField(
                        max_length=50, null=True, verbose_name="AEB自動緊急煞車系統"
                    ),
                ),
                (
                    "電子煞車力分配系統",
                    models.CharField(
                        max_length=50, null=True, verbose_name="電子煞車力分配系統"
                    ),
                ),
                ("EBS", models.CharField(max_length=50, null=True, verbose_name="EBS")),
                (
                    "雷達碰撞預防系統",
                    models.CharField(max_length=50, null=True, verbose_name="雷達碰撞預防系統"),
                ),
                (
                    "自動停車系統",
                    models.CharField(max_length=50, null=True, verbose_name="自動停車系統"),
                ),
                (
                    "雙前座正面氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="雙前座正面氣囊"),
                ),
                (
                    "雙前座側面氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="雙前座側面氣囊"),
                ),
                (
                    "前座中央防碰撞氣囊",
                    models.CharField(
                        max_length=50, null=True, verbose_name="前座中央防碰撞氣囊"
                    ),
                ),
                (
                    "右前座膝部氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="右前座膝部氣囊"),
                ),
                (
                    "右前座正面氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="右前座正面氣囊"),
                ),
                (
                    "後座側面氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="後座側面氣囊"),
                ),
                (
                    "駕駛座正面氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="駕駛座正面氣囊"),
                ),
                (
                    "駕駛座膝部氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="駕駛座膝部氣囊"),
                ),
                (
                    "雙前座膝部氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="雙前座膝部氣囊"),
                ),
                (
                    "左後座腿靠氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="左後座腿靠氣囊"),
                ),
                (
                    "右後座防潛滑氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="右後座防潛滑氣囊"),
                ),
                (
                    "右後座腿靠氣囊",
                    models.CharField(max_length=50, null=True, verbose_name="右後座腿靠氣囊"),
                ),
            ],
            options={
                "ordering": [
                    "類型",
                    "車種",
                    "VIN",
                    "中文等級",
                    "出廠年月",
                    "排氣量_x",
                    "車身型式",
                    "車重",
                    "價格_x",
                    "車牌號碼",
                    "價格_y",
                    "車身座位",
                    "變速系統",
                    "動力型式",
                    "定速巡航",
                    "蜂鳴式倒車輔助系統",
                    "倒車影像輔助",
                    "前方駐車雷達",
                    "循跡防滑控制系統",
                    "車道偏離警示系統",
                    "車道變換輔助系統",
                    "ACC主動跟車系統",
                    "車道維持輔助系統",
                    "AEB自動緊急煞車系統",
                    "電子煞車力分配系統",
                    "EBS",
                    "雷達碰撞預防系統",
                    "自動停車系統",
                    "雙前座正面氣囊",
                    "雙前座側面氣囊",
                    "前座中央防碰撞氣囊",
                    "右前座膝部氣囊",
                    "右前座正面氣囊",
                    "後座側面氣囊",
                    "駕駛座正面氣囊",
                    "駕駛座膝部氣囊",
                    "雙前座膝部氣囊",
                    "左後座腿靠氣囊",
                    "右後座防潛滑氣囊",
                    "右後座腿靠氣囊",
                ],
            },
        ),
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("complete", models.BooleanField()),
                (
                    "todolist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Vincode.mymodel",
                    ),
                ),
            ],
        ),
    ]
