# Generated by Django 4.2.7 on 2023-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vincode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combinelexus",
            options={
                "ordering": [
                    "類型",
                    "車種",
                    "VIN",
                    "中文等級",
                    "出廠年月",
                    "排氣量_x",
                    "車身型式",
                    "車重",
                    "價格_x",
                    "車牌號碼",
                    "價格_y",
                    "車身座位",
                    "變速系統",
                    "動力型式",
                    "定速巡航",
                    "蜂鳴式倒車輔助系統",
                    "倒車影像輔助",
                    "前方駐車雷達",
                    "循跡防滑控制系統",
                    "車道偏離警示系統",
                    "車道變換輔助系統",
                    "ACC主動跟車系統",
                    "車道維持輔助系統",
                    "AEB自動緊急煞車系統",
                    "電子煞車力分配系統",
                    "EBS",
                    "雷達碰撞預防系統",
                    "自動停車系統",
                    "雙前座正面氣囊",
                    "雙前座側面氣囊",
                    "前座中央防碰撞氣囊",
                    "右前座膝部氣囊",
                    "右前座正面氣囊",
                    "後座側面氣囊",
                    "駕駛座正面氣囊",
                    "駕駛座膝部氣囊",
                    "雙前座膝部氣囊",
                    "左後座腿靠氣囊",
                    "右後座防潛滑氣囊",
                    "右後座腿靠氣囊",
                ]
            },
        ),
        migrations.RemoveField(
            model_name="combinelexus",
            name="引擎車身碼",
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="ACC主動跟車系統",
            field=models.CharField(max_length=50, null=True, verbose_name="ACC主動跟車系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="AEB自動緊急煞車系統",
            field=models.CharField(
                max_length=50, null=True, verbose_name="AEB自動緊急煞車系統"
            ),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="EBS",
            field=models.CharField(max_length=50, null=True, verbose_name="EBS"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="VIN",
            field=models.CharField(max_length=50, null=True, verbose_name="VIN"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="倒車影像輔助",
            field=models.CharField(max_length=50, null=True, verbose_name="倒車影像輔助"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="價格_x",
            field=models.CharField(max_length=50, null=True, verbose_name="價格_x"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="價格_y",
            field=models.CharField(max_length=50, null=True, verbose_name="價格_y"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="前座中央防碰撞氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="前座中央防碰撞氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="前方駐車雷達",
            field=models.CharField(max_length=50, null=True, verbose_name="前方駐車雷達"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="動力型式",
            field=models.CharField(max_length=50, null=True, verbose_name="動力型式"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="右前座正面氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="右前座正面氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="右前座膝部氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="右前座膝部氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="右後座腿靠氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="右後座腿靠氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="右後座防潛滑氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="右後座防潛滑氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="定速巡航",
            field=models.CharField(max_length=50, null=True, verbose_name="定速巡航"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="左後座腿靠氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="左後座腿靠氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="後座側面氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="後座側面氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="循跡防滑控制系統",
            field=models.CharField(max_length=50, null=True, verbose_name="循跡防滑控制系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="排氣量_x",
            field=models.CharField(max_length=50, null=True, verbose_name="排氣量_x"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="自動停車系統",
            field=models.CharField(max_length=50, null=True, verbose_name="自動停車系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="蜂鳴式倒車輔助系統",
            field=models.CharField(max_length=50, null=True, verbose_name="蜂鳴式倒車輔助系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="變速系統",
            field=models.CharField(max_length=50, null=True, verbose_name="變速系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車牌號碼",
            field=models.CharField(max_length=50, null=True, verbose_name="車牌號碼"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車身型式",
            field=models.CharField(max_length=50, null=True, verbose_name="車身型式"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車身座位",
            field=models.CharField(max_length=50, null=True, verbose_name="車身座位"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車道偏離警示系統",
            field=models.CharField(max_length=50, null=True, verbose_name="車道偏離警示系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車道維持輔助系統",
            field=models.CharField(max_length=50, null=True, verbose_name="車道維持輔助系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車道變換輔助系統",
            field=models.CharField(max_length=50, null=True, verbose_name="車道變換輔助系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="車重",
            field=models.CharField(max_length=50, null=True, verbose_name="車重"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="雙前座側面氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="雙前座側面氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="雙前座正面氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="雙前座正面氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="雙前座膝部氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="雙前座膝部氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="雷達碰撞預防系統",
            field=models.CharField(max_length=50, null=True, verbose_name="雷達碰撞預防系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="電子煞車力分配系統",
            field=models.CharField(max_length=50, null=True, verbose_name="電子煞車力分配系統"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="類型",
            field=models.CharField(max_length=50, null=True, verbose_name="類型"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="駕駛座正面氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="駕駛座正面氣囊"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="駕駛座膝部氣囊",
            field=models.CharField(max_length=50, null=True, verbose_name="駕駛座膝部氣囊"),
        ),
        migrations.AlterField(
            model_name="combinelexus",
            name="中文等級",
            field=models.CharField(max_length=50, null=True, verbose_name="中文等級"),
        ),
        migrations.AlterField(
            model_name="combinelexus",
            name="出廠年月",
            field=models.CharField(max_length=50, null=True, verbose_name="出廠年月"),
        ),
        migrations.AlterField(
            model_name="combinelexus",
            name="車種",
            field=models.CharField(max_length=50, null=True, verbose_name="車種"),
        ),
    ]
