# Generated by Django 4.2.7 on 2023-12-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Vincode", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combinelexus",
            options={
                "ordering": [
                    "類型",
                    "車種",
                    "VIN",
                    "中文等級",
                    "出廠年月",
                    "排氣量_x",
                    "車身型式",
                    "車重",
                    "價格_x",
                    "車牌號碼",
                    "價格_y",
                    "CARMDL",
                    "SFX",
                    "車身座位",
                    "變速系統",
                    "動力型式",
                    "定速巡航",
                    "蜂鳴式倒車輔助系統",
                    "倒車影像輔助",
                    "前方駐車雷達",
                    "循跡防滑控制系統",
                    "車道偏離警示系統",
                    "車道變換輔助系統",
                    "ACC主動跟車系統",
                    "車道維持輔助系統",
                    "AEB自動緊急煞車系統",
                    "電子煞車力分配系統",
                    "EBS",
                    "雷達碰撞預防系統",
                    "自動停車系統",
                    "雙前座正面氣囊",
                    "雙前座側面氣囊",
                    "前座中央防碰撞氣囊",
                    "右前座膝部氣囊",
                    "右前座正面氣囊",
                    "後座側面氣囊",
                    "駕駛座正面氣囊",
                    "駕駛座膝部氣囊",
                    "雙前座膝部氣囊",
                    "左後座腿靠氣囊",
                    "右後座防潛滑氣囊",
                    "右後座腿靠氣囊",
                ]
            },
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="CARMDL",
            field=models.CharField(max_length=50, null=True, verbose_name="CARMDL"),
        ),
        migrations.AddField(
            model_name="combinelexus",
            name="SFX",
            field=models.CharField(max_length=50, null=True, verbose_name="SFX"),
        ),
    ]
